// src/app/dto/artistDto.ts

export interface ArtistDto {
    id?: string;  // Optional since it will be generated by the backend
    artistName: string;
    stageName?: string; // Optional
    numberOfAlbums?: number; // Optional
    artistImage?: string; // Optional
    careerStartDate: string;
    socialMediaLinks?: string[]; // Optional
    recordLabel?: string; // Optional
    publishingHouse?: string; // Optional
    rating?: number; // Optional, default to 0
}
